app/tls/__init__.py
#    -*- coding: utf-8 -*-
from flask import Blueprint

tls = Blueprint('tls', __name__,
                template_folder='templates',
                static_folder='static'
)

from . import views, errors
#from ..models import Permission


# @main.app_context_processor
# def inject_permissions():
#     return dict(Permission=Permission)

app/tls/views.py
#    -*- coding: utf-8 -*-
from __future__ import unicode_literals
from flask import Response, session, render_template, redirect, url_for, abort, flash, Markup, request,\
    current_app, make_response, send_from_directory, g
from flask.ext.login import current_user
from flask.ext.babel import gettext, ngettext
#from flask.ext.sqlalchemy import get_debug_queries
## github authentication [2015-10-03T17:08:15+0900]
from werkzeug.contrib.fixers import ProxyFix
from flask_dance.contrib.github import make_github_blueprint, github
from jinja2 import Environment, PackageLoader
from github import Github
import urllib

from . import tls
# from .forms import EditProfileForm, EditProfileAdminForm, PostForm,\
#     CommentForm
from .. import db
from .. import redis_store
from .. import tlsdb
from .. import lib
from .. import babel
#from ..models import Permission, Role, User, Post, Comment
#from ..decorators import admin_required, permission_required
from collections import Counter

from datetime import datetime
import subprocess

from collections import defaultdict

import codecs, re
from .. import mandoku_view
import git, requests, sys


reload(sys)
sys.setdefaultencoding('utf-8')
kr_user = "kr_user:"
zbmeta = "kr:meta:"
titpref = "kr:title:"

tls_root = "/home/chris/tlsdev/krp/tls/lexicon/"
swl_txt = tls_root + "index/swl.txt"
swl_key = "swl::"
syl_txt = tls_root + "index/syllables.txt"
syl_key = "syl::"
syn_txt = tls_root + "index/syn-func.txt"
funx = {"syn-func" : "syn-func::", "sem-feat" : "sem-feat::"}
char_txt = tls_root + "core/characters.tab"
char_key = "char::"
con_dir = tls_root + "concepts/"
con_key = "con::"
zhu_dir = tls_root + "notes/zhu/"
zhu_key = "zhu::"
ft_key = "ft::"
uuid_key= "uuid:"
tax_key = "tax::"

link_re = re.compile(r'\[\[([^\]]+)\]\[([^\]]+)')
hd = re.compile(r"^(\*+) (.*)$")
#env = Environment(loader=PackageLoader('__tls__', 'templates'))


def static_from_root():
    return send_from_directory(current_app.static_folder, request.path[1:])

#@tls.route('/concept/<id>', methods=['GET', 'POST',])
#def display_concept(id):
#    c=redis_store.hgetall("%s%s" % (con_key,id))

@tls.route('/index', methods=['GET',])
def tls_index():
    """Show the start page for tls"""
    return


# @tls.route('/<coll>/search', methods=['GET', 'POST',])
# @tls.route('/search', methods=['GET', 'POST',])
# def searchconcept(count=20, page=1):
#     rsort=""
#     sort = request.values.get('sort', '')
#     q = request.values.get('query', '')

@tls.route('/concept', methods=['GET'],)
@tls.route('/concept/<concept_id>', methods=['GET'],)
def showconcept(concept_id=None):
    if concept_id:
        print "id:", concept_id
    else:
        concept_id=request.values.get('id', 'ADMIRE')
    print "id:, ", concept_id
    res = tlsdb.hgetall(con_key + concept_id)
    print len(res)
    for k in res.keys():
        kn = k.replace("+", "")
        try:
            res[kn] = eval(res[k])
        except:
            pass
    return render_template('concept.html', c=res)



@tls.route('/index', methods=['GET',])
@tls.route('/', methods=['GET',])
def index():
    return render_template('tls.html', concept="START")
#    return "INDEX"
@tls.route('/concepts/browse', methods=['GET',])
def concepttree():
    s=request.values.get("query", "PRIME")
    r=tlsdb.hgetall(con_key+s)
    try:
        p = eval(r['pointers'])
    except:
        p = {'NO POINTER' : []}
    res = p
    t = []
    # get the tree for s
    while p.has_key("KIND OF"):
        t.append(p["KIND OF"][0])
        r=tlsdb.hgetall(con_key + p["KIND OF"][0])
        #print r
        try:
            p = eval(r['pointers'])
        except:
            p = {'NO POINTER' : []}
    # search for concepts, 
    return render_template('tlstaxtree.html', res=res, q=s, tree=t)

def redirect_url(default='index'):
    return request.args.get('next') or \
           request.referrer or \
           url_for(default)

@tls.route('/synfunc/browse', methods=['GET',])
def synfunctree():
    s=request.values.get("query", "{CONSTITUENT}")
    try:
        kx=tlsdb.lrange(ft_key+ "" + s, 0, -1)[0]
    except:
        flash("Your query for %s returned no results!" % (s)  )
        return redirect(redirect_url())
    r=tlsdb.hgetall(kx.split("@")[-1])
    uuid = r['uuid']
    res = []
    try:
        p = eval(r['pointers'])
    except:
        p = {'NO POINTER' : []}
    for pt in p:
        r=tlsdb.hgetall(funx['syn-func'] + pt[0])
        #print pt[0], r.keys()
        try:
            inst = eval(r['inst'])
        except:
            inst = []
        pt.append(len(inst))
        res.append(pt)
    t = []
    try:
        ul = eval(r["uplink"])
    except:
        ul = {'NO POINTER' : []}
    while len(ul) > 1:
        t.append(ul)
        r=tlsdb.hgetall(ul[0])
        try:
            ul = eval(r['uplink'])
        except:
            ul = {'NO POINTER' : []}
    return render_template('tlssyntree.html', res=res, q=s, tree=t, uuid=uuid)


@tls.route('/search', methods=['GET',])
def ftsearch():
    # give the start of the concept tree, at the given concept
    s=request.values.get("query", "N/A")
    key = s
    ctax = tlsdb.hgetall(tax_key + s)
    #print ctax
    if not s.endswith("="):
        s += "*"
    ftk = tlsdb.keys(ft_key + s)
    if len(ftk) < 1:
        s = s.upper()
        ftk = tlsdb.keys(ft_key + s)
    res = [(a.split("::")[1], tlsdb.lrange(a, 0, -1)) for a in ftk]
    return render_template('tlssearch.html', res=res, key=key,
                           ldic={"con" : "Concept",
                                "def" : "Definition",
                                "sw" : "Word",
                                "csyn" : "Synonym",
                                "synf" : "Syntactic function",
                                "synd" : "Def. of syntactic function",
                                "czh" : u"現代漢語",
                                "coch" : u"古代漢語",
                           },
                           ct = ctax,
                           ts = len(res)
    )


@tls.route('/func/<type>/<uuid>', methods=['GET',])
def showsynsem(type=None, uuid=None):
    res=tlsdb.hgetall(funx[type]+uuid)
    inst=eval(res['inst'])
    new=[]
    for i in inst:
        l = tlsdb.lrange(swl_key+i, 0, -1)
        for b in [a.split("##") for a in l]:
            f = {'loc': b[0], 'char': b[4], 'line': b[5], 'title' : b[1]}
            new.append(f)
    cnt = len(new)
    res['inst'] = new[0:1000]
    
    return render_template("funx.html", res=res, cnt=cnt)


#@main.route('/text/<id>/', methods=['GET',])
@tls.route('/text/<loc>', methods=['GET',])
@tls.route('/text/<id>/<juan>', methods=['GET',])
#@main.route('/edition/<branch>/<id>/<juan>', methods=['GET',])
#@main.route('/edition/<branch>/<id>/', methods=['GET',])
def showtext(juan="Readme.org", id=0, coll=None, seq=0, branch="master", user="kanripo", loc=""):
    rp = False
    editurl=False
    showtoc = True
    doc = {}
    uid = user
    token = ""
    fn = ""
    key = request.values.get('query', '')
    if user=='tls-kr':
        branch = "tls-annot"
    if len(loc) > 0:
        floc = loc.split(":")
        id = floc[0].split("_")[0]
        juan = floc[0].split("_")[1]
        if key == '':
            key = floc[-1]
        print id, juan, key
    try:
        juan = "%3.3d" % (int(juan))
    except:
        showtoc = False
    if coll:
        #TODO: allow for different repositories, make this configurable
        if coll.startswith('KR'):
            id = "%s%4.4d" % (coll, int(seq))
        else:
            #TODO need to find the canonical id for this, go to redis, pull it out
            id="Not Implemented"
    #the filename is of the form ZB1a/ZB1a0001/ZB1a0001_002.txt
    if "user" in session:
        user = session['user']
        uid = user
        user_settings=redis_store.hgetall("%s%s:settings" % (kr_user, user))
        if user_settings.has_key(id):
            uidbranch = user_settings[id].split("/")
            branch=uidbranch[-1]
            uid = uidbranch[0]
            token="%s" % (session['token'])            
    #print uid, user
    if juan.startswith("Readme"):
        url =  "https://raw.githubusercontent.com/%s/%s/%s/%s" % (uid, id, branch, juan)
        xediturl =  "https://github.com/%s/%s/edit/%s/%s" % (uid, id, branch, juan,)
    else:
        url =  "https://raw.githubusercontent.com/%s/%s/%s/%s_%s.txt" % (uid, id, branch,  id, juan)
        xediturl =  "https://github.com/%s/%s/edit/%s/%s_%s.txt" % (uid, id, branch,  id, juan,)
    # url =  "https://raw.githubusercontent.com/kanripo/%s/%s/%s_%s.txt?client_id=%s&client_secret=%s" % (id, branch,  id, juan,
    #     current_app.config['GITHUB_OAUTH_CLIENT_ID'],
    #     current_app.config['GITHUB_OAUTH_CLIENT_SECRET'])
    if "token" in session:
        g=Github(session['token'])
        rp = g.get_repo("%s/%s" % (uid, id))
        try:
            rpn=rp.full_name
        except:
            try:
                rp = g.get_repo("tls-kr/%s" % (id))
                rpn=rp.full_name
            except:
                try:
                    rp = g.get_repo("kanripo/%s" % (id))
                    rpn=rp.full_name
                except:
                    rpn="No repository found!"
                    rp = False
    #print rpn
    if rp:
        fn = rp.get_file_contents("%s_%s.txt" % (id, juan), ref=branch).decoded_content.decode('utf-8')
    else:
        r = requests.get(url, auth=(user, token))
        print url, r.status_code
        if r.status_code == 200:
            fn = r.content
            editurl = xediturl
        else:
            if juan.startswith("Readme"):
                url =  "https://raw.githubusercontent.com/%s/%s/%s/%s" % (current_app.config['GHKANRIPO'], id, branch, juan,)
            else:
                url =  "https://raw.githubusercontent.com/%s/%s/%s/%s_%s.txt" % (current_app.config['GHKANRIPO'], id, branch,  id, juan,)
                r = requests.get(url)
                if r.status_code == 200:

app/tls/templates/concept.html
{% extends "tlsbase.html" %}

{% block title %}TLS{% endblock %}

{% block body %}

<div class="row">
  <div id="txtcont" class="span9">
    <h2>{{c.concept}} 
      {% if c.TR_OCH %} (古: {{c.TR_OCH}}) {% endif %} /
      {% if c.TR_ZH %} (現: {{c.TR_ZH}}) {% endif %}
      <a style="font-size: 50%" title="Show the alternate concept labels" onclick="show_h5('alt-labels')">Labels</a>
    </h2>
    <div class="syn" style="display:none" id="alt-labels">
      <ul>
      {% for s in c.SYNONYM %}
      <li>{{s}}</li>
      {% endfor %}
      </ul>
    </div>
    <div class="definition">
      <pre>{{c.def}}</pre>
    </div>  
    <div class="pointers">
      {% for k in c.pointers %}
      {% if c.pointers[k] %}
      <h3>{{k}}</h3>
      <ul>
      {% for v in c.pointers[k] %}
      <li><a href="{{url_for('.showconcept')}}?id={{v}}">{{v}}</a></li>
      {% endfor %}
      </ul>
      {% endif %}
      {% endfor %}
    </div>
    <div class="words">
      <h3>Words
　　	<a title="Show the syntactic word entries for all Lexemes" onclick="show_swl(uuid='CONCEPT-{{c.concept}}')">Show all examples</a>
      </h3>
      <ul id="SWCONCEPT-{{c.concept}}"></ul>
      {% for w in c.words %}
      {% set wrd = w['head'].split()[0] %}
      {% set uuid = w['CUSTOM_ID'] %}
      <hr/>
      <h4 id="{{uuid}}">{{loop.index}} {{w['head']}}
	<a title="Show the syntactic word entries for this Lexeme" onclick="show_h5(uuid='H5-{{uuid}}')">Syntactic words</a>
	<!--
	| 
	<a title="This will search for this word and allow you to select example sentences." href="{{url_for('main.searchtext', query=wrd, filter='$tls', type='tls', action='add_attr', uuid=uuid)}}">Add example</a> -->
      </h4>
      <div id="H5-{{uuid}}" style="display:none;"/>
      {% for s in w['synwords'] %}
      {% if s['head'] != 'SOURCE REFERENCES' %}
      <h5>
      {% for sf in s['funx'] %}
      <a href="{{url_for('.showsynsem', type=sf[0], uuid=sf[1])}}">{{sf[2]}}</a> 
      {% endfor %}
      </h5>
      <pre>{{s.def}}</pre>
      <a  id="{{s.CUSTOM_ID}}" onclick="show_swl(uuid='{{s.CUSTOM_ID}}')">Show examples</a>
      <ul id="SW{{s.CUSTOM_ID}}">
      </ul>
      {% if s.not %}
      <p>{{s.not}}</p>
      {% endif %}  <!-- ends notes -->
      {% endif %}  <!-- ends check for source references -->
      {% endfor %}
      </div>
      {% endfor %}
    </div>  
  </div>
</div>  
{% endblock %}
    
{% block closingscript %}
<script>
  function show_h5x(uid){
  var x = document.getElementById(uid);
  if (x.style.display === 'none')
  { x.style.display = 'block'; }
  else
  { x.style.display = 'none'; }
  };
  
  function show_h5 (uid){
//  var x = $('#' + uid).css("display");
//  alert(x);
  if ($('#' + uid).css("display") != "block"){
  $('#' + uid).css({"display" : "block"});
  } else {
//  alert(uid);
  $('#' + uid).css({"display" : "none"});
  }
  };
  function show_swl(uid){
//  alert(uid);
  $.ajax({
  type : "GET",
  url : "{{url_for('.showex', uuid=uid)}}" + uid, 
//  url : "{{url_for('.showex', uuid=uid)}}",
  success : function(resp){
  $('#SW' + uid).html(resp)
  },
  });
  };
  (function($) {
  $(document).ready(function() {
//  $('#update').click(function() {  
  })})(jQuery);

</script>

{% endblock %}

app/tls/templates/funx.html
{% extends "tlsbase.html" %}

{% block title %}TLS{% endblock %}

{% block body %}

<div class="row">
  <div id="txtcont" class="span9">
    <h2>{% if res['syn'] %} Syntactic function:  {{res['syn']}} {% endif %}
      {% if res['sem-feat'] %} Semantic feature:  {{res['sem-feat']}} {% endif %}
    </h2>
    {% if res['syn'] %} <p>Syntactic function tree: <a href="{{url_for('tls.synfunctree', query=res['syn'])}}">{{res['syn']}}</a></p> {% endif %}
    <p><b>{{res['def']}}</b><p>
      {% if res.inst %}
    <p>There are {{cnt}} attributions recorded in the TLS:
      {% if cnt > 1000 %}
      (showing only the first 1000)
      {% endif %}
    </p>
      {% endif %}
    <div class="syn">
      <ul>
	{% for s in res.inst %}
	{% if s.loc %}
	{% set txtloc = s['loc'].split(':') %}
	{% set it_txtid, it_juan = txtloc[0].split('_') %}
	<!-- stupid hack, fails in 30% -->
	{% set it_page = txtloc[1].split('a')[0] + 'a' %}
	{% set ch = s.char.split('@')[0] %}
	{% set py = s.char.split('@')[1] %}
	<li><b>{{ch}} {{py}}</b><br/>
	  {{s.line}} ( <a href="{{url_for('tls.showtext', id=it_txtid, juan=it_juan, query=txtloc[-1], _anchor=it_juan+'-'+it_page, user='tls-kr')}}">{{s.title}}</a>)</li>
	{% endif %}
      {% endfor %}
      </ul>
    </div>  
  </div>
</div>  
{% endblock %}
    
{% block closingscript %}
<script>
  (function($) {
  $(document).ready(function() {
  $('#update').click(function() {  
  })(jQuery);

  function show_swl(var uuid){
  
  };
</script>

{% endblock %}

app/tls/templates/tls.html
{% extends "tlsbase.html" %}

{% block body %}

<div id="introduction">
<h2>Main Features</h2>
<ul><li>
The Thesaurus Linguae Sericae (TLS) is designed as as a collaborative forum for discussion on the close reading of Chinese texts.
</li><li>
TLS provides a corpus of classical Chinese texts wherever possible with interlinear translations. 
</li><li>
TLS links the texts incorporated with an analytic dictionary of the Chinese language.
</li><li>
TLS pays special attention to historical keywords.
</li><li>
TLS works towards a cross-cultural study of conceptual history.
</li><li>
TLS compiles a detailed synonym dictionary of Chinese.
</li><li>
TLS systematically organises the Chinese vocabulary in <a href="{{url_for('tls.concepttree')}}">taxonomic hierarchies of synonym groups.</a>
</li><li>
TLS develops a system of <a href="{{url_for('tls.synfunctree')}}">syntactic categories</a> for the analysis of Chinese texts.
</li><li>
TLS develops a system of rhetorical devices for the analysis of Chinese texts.
</li><li>
TLS deploys a system of standard semantic relations<!--like antonym, converse, epithet, etc. between words-->, <!--thereby--> aiming to define the Chinese conceptual space as a relational space.
</li><li>
TLS seeks to make available up-to-date databases on historical phonology and the history of Chinese characters.
</li>
</ul>
<h2>Cautionary Notes</h2>
<ul>
<li>This database is no more than an on-line construction site.
</li><li>
Due to lack of funding<!--over more than the twenty years of its persistently precarious existence-->, <!--precious --> very little in TLS has so far been proofread or double-checked. <em>Caveat lector!</em>
</li><li>
TLS encourages suggestions for improvement at the bottom of every page. 
</li>
</ul>
</p>
<b>Please acknowledge your use of TLS in your publications.</b>

</div>

{% endblock %}

app/tls/templates/tlsbase.html
<!DOCTYPE html>
<html>
  <head>
    <title>TLS - Thesaurus Linguae Sericae 漢學文典 </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='jquery/jquery.ui.core.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='jquery/jquery.ui.tabs.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='jquery/jquery.ui.theme.css')}}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="{{url_for('static', filename='css/bootstrap.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='css/docs.css')}}" rel="stylesheet"> 
    <link href="{{url_for('static', filename='css/mdweb.css')}}" rel="stylesheet"> 

    {% block head %}{% endblock head %}
  </head>
  <body onload="highlightSearchTerms('{{key}}');" data-spy="scroll" data-target=".bs-docs-sidebar">
    {% block navbar %}

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a href="{{url_for('tls.index')}}" class="pull-left" title="{{_('Kanseki Repository')}}">
	<img width="40" height="40" src="{{ url_for('static', filename='img/kanripo-64.png')}}"/>
	</a>
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar">	</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="{{url_for('main.index')}}">
	  {% block KR %}
	  {% endblock KR %}
      </a>
      <div class="nav-collapse collapse">
        <ul class="nav">
	  <!--          <li class="active"><a href="/texts/dzjy">{{_('Collections')}}</a></li> -->
	  {% block navlinks %}
          <li class="active"><a href="{{url_for('main.catalog')}}">{{_('KR Catalog')}}</a></li>
          <li class="active"><a href="{{url_for('tls.concepttree')}}">{{_('Concepts')}}</a></li>
	  <li><a href="http://blog.kanripo.org">Blog</a></li>
	  {% endblock navlinks%}
        </ul>
      </div>
        <ul class="nav pull-right">
	<li class="active"><a href="{{url_for('main.contact')}}">{{_('Contact')}}</a></li>
{% if session['user'] %}
<li  class="label-important"><a href="{{url_for('main.profile', uid=session['user'])}}">{{session['user']}}</a></li>
{% else %}
<li class="label-important"><a href="{{url_for('main.login')}}">{{_('Login')}}</a></li>
{% endif %}
      </ul>
      <form class="navbar-search pull-right" action="{{url_for('main.searchtext')}}" method="GET">
	<input size="10" name="query" id="query" type="text" class="search-query" placeholder="{{_('Text Search')}}">
      </form>
      <form class="navbar-search pull-right" action="{{url_for('tls.ftsearch')}}" method="GET">
	<input  size="5" name="query" id="query" type="text" class="search-query" placeholder="{{_('TLS Search')}}">
      </form>


    </div>
  </div>
</div>

{% endblock navbar %}

{% block subhead %}

<header class="jumbotron subhead" id="overview">
  <div class="container">
    <h1>{{_('漢學文典 TLS - Thesaurus Linguae Sericae')}}</h1>
    <p class="lead">{{_('An Historical and Comparative Encyclopaedia of Chinese Conceptual Schemes.')}}</p>
  </div>
</header>

{% endblock subhead %}


<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

  <div class="row">
    <div id="sidebardiv" class="span2">
      {% block sidebar %}
    <h2>{{_('News')}}</h2>
    {% endblock sidebar %}
    </div>

    <div id="maintextdiv" class="span9 textbody">
      {% block body %}{% endblock %}
    </div>
    <div id="imagediv" class="span1 hidden" style="margin-left:20px;">
      <div id="imageinner">
	<div class="buttons">
	  <div class="dropdown">
	    <!-- Link or button to toggle dropdown -->
	    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
	      <li><a tabindex="-1" href="#">Action</a></li>
	      <li><a tabindex="-1" href="#">Another action</a></li>
	      <li><a tabindex="-1" href="#">Something else here</a></li>
	      <li class="divider"></li>
	      <li><a tabindex="-1" href="#">Separated link</a></li>
	    </ul>
	  </div>    
	  <button class="pz-close" title="{{_('Close')}}">{{_('X')}}</button>
	  <button class="zoom-in"  title="{{_('Enlarge')}}">{{_('+')}}</button>
	  <button class="zoom-out"  title="{{_('Shrink')}}">{{_('-')}}</button>
	  <input type="range" class="zoom-range">
	  <button class="reset"  title="{{_('Reset')}}">{{_('⟲')}}</button>
	  <button class="pz-prev"  title="{{_('Previous page')}}" >&lt;</button>
	  {% block edoption %}{% endblock %}
	  <button class="pz-next"  title="{{_('Next page')}}" >&gt;</button>
	</div>
	<div id="imgcont">
	  <div class="panzoom">
	  </div>
	</div>
      </div>
    </div>
</div> <!-- closes row -->
</div>
    <script  src="{{ url_for('static', filename='jquery/jquery.js')}}"></script>
    <script  src="{{ url_for('static', filename='jquery/jquery.ui.core.js')}}"></script>
    <script  src="{{ url_for('static', filename='jquery/jquery.ui.widget.js')}}"></script>
    <script  src="{{ url_for('static', filename='jquery/jquery.ui.tabs.js')}}"></script>
    <script  src="{{ url_for('static', filename='js/highlight.js')}}"></script>
    <script src="{{ url_for('static', filename='js/jquery.panzoom.js')}}"></script>
    {% block closingscript %}
    {% endblock %}
    {% block footer %}
    <div id="footer">
      <div class="container">
	<p><a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a>
	  {{_('(c) TLS - Thesaurus Linguae Sericae. All content created by us is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/" title="Creative Commons Attribution-ShareAlike 4.0 International License">CC BY SA</a> license. ')}}
	  <!-- Users retain copyright of their contributions.--> </p>
      </div>
    </div>    
    {% endblock %}
  </body>
</html>

app/tls/templates/tlssearch.html
{% extends "tlsbase.html" %}

{% block body %}

<h1>TLS - Thesaurus Linguae Sericae 漢學文典 </h1>
<p>{{_('Searched for %(value)s. ', value=key)}}</p>
{{_('Found %(total)d', total=ts)}}
<p>{{ct['tax']|safe}}</p>
<hr/>
<table style="border: 1px solid black;">
  {% for item in res|sort %}
  {% set it_res = item[1] %}
  <tr>
    <td class="text-left" style="border: 1px solid black;">{{item[0]}}</td>
    <td style="border: 1px solid black;">
      <ul>
	{% for nit in it_res|sort %}
	<li>
	  {% set concept = nit.split("@")[-1].split("::")[-1] %}
	  {% set rtype = nit.split("@")[0].split("=")[0] %}
	  {% set stype = nit.split("@")[1] %}
	  {% if rtype == 'synf' %}
	  <a title="{{ldic[rtype]}}" href="{{url_for('tls.showsynsem', uuid=concept, type='syn-func')}}">{{item[0]}}</a>
	  {% else %}
	  {% if rtype == 'synd' %}
	  <a title="{{ldic[rtype]}}" href="{{url_for('tls.showsynsem', uuid=concept, type='syn-func')}}">{{stype}}</a>
	  {% else %}
	  {% if rtype == 'sw' %}
	  {% set anchor = nit.split("@")[0].split("=")[1] %}
	  <a title="{{ldic[rtype]}}" href="{{url_for('tls.showconcept', id=concept, _anchor=anchor)}}">{{concept}}</a>
	  {% else %}
	  <a title="{{ldic[rtype]}}" href="{{url_for('tls.showconcept', id=concept)}}">{{concept}}</a>
	  {% endif %}
	  {% endif %}
	  {% endif %}
	  </li>
	  {% endfor %}
      </ul>
    </td>
  </tr>
  {% endfor %}
</table>
    <p><a href="{{url_for('tls.concepttree')}}">Browse the concepts</a> | 
    <a href="{{url_for('tls.synfunctree')}}">Browse the syntactic functions</a></p>
{% endblock %}

app/tls/templates/tlssyntree.html
{% extends "tlsbase.html" %}

{% block body %}

<h2><a href="{{url_for('tls.showsynsem', type='syn-func', uuid=uuid)}}">{{q}}</a> </h2>

{% for item in tree %}
<a title="POINTER" href="{{url_for('tls.synfunctree', query=item[1])}}">{{item[1]}}</a>&nbsp;→
{% endfor %}
<ul>
  {% for item in res %}
  <li><a title="POINTER" href="{{url_for('tls.synfunctree', query=item[1])}}">{{item[1]}}</a>　　　<b title="CONCEPT">Syntactic function: <a href="{{url_for('tls.showsynsem', type='syn-func', uuid=item[0])}}">{{item[1]}}</a></b> ({{item[2]}} instances)</li>
    {% endfor %}
    </ul>

    
{% endblock %}

app/tls/templates/tlstaxtree.html
{% extends "tlsbase.html" %}

{% block body %}

    <h2>{{q}}</h2>
    {% for item in tree %}
    <a title="POINTER" href="{{url_for('tls.concepttree', query=item)}}">{{item}}</a>&nbsp;→
    {% endfor %}
    {% for ptype in res.keys() %}
    <h3>{{ptype}}</h3>
    <ul>
      {% for item in res[ptype] %}
      <li><a title="POINTER" href="{{url_for('tls.concepttree', query=item)}}">{{item}}</a>　　　<b title="CONCEPT">Concept: <a href="{{url_for('tls.showconcept', id=item)}}">{{item}}</a></b></li>
      {% endfor %}
    </ul>
    {% endfor %}
    
{% endblock %}